# Generated by Django 3.2.9 on 2022-04-22 14:30

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('born_date', models.DateField(help_text='YYYY-MM-DD', validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)])),
                ('country_born', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Actor',
                'verbose_name_plural': 'Actors',
                'unique_together': {('first_name', 'last_name', 'born_date')},
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('born_date', models.DateField(help_text='YYYY-MM-DD', validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)])),
                ('country_born', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directors',
                'unique_together': {('first_name', 'last_name', 'born_date')},
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title on the english language', max_length=200)),
                ('original_title', models.CharField(help_text='title on the original language', max_length=200)),
                ('release_date', models.DateField(help_text='YYYY-MM-DD')),
                ('post_date', models.DateField(auto_now_add=True, help_text='YYYY-MM-DD')),
                ('description', models.TextField(max_length=1024)),
                ('continuance', models.PositiveIntegerField()),
                ('small_img', models.ImageField(default='img/film_img/small/default.jpg', upload_to='img/film_img/small/')),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField()),
                ('actor', models.ManyToManyField(to='films_review.Actor')),
                ('country', models.ManyToManyField(to='films_review.Country')),
                ('director', models.ManyToManyField(to='films_review.Director')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Films',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('born_date', models.DateField(help_text='YYYY-MM-DD', validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)])),
                ('country_born', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Writer',
                'verbose_name_plural': 'Writers',
                'unique_together': {('first_name', 'last_name', 'born_date')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('text', models.TextField(max_length=8192)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films_review.film')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='FilmImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='img/film_img/big/default.jpg', upload_to='img/film_img/big/')),
                ('is_active', models.BooleanField(default=True)),
                ('film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IMAGE', to='films_review.film')),
            ],
            options={
                'verbose_name': 'Film image',
                'verbose_name_plural': 'Film images',
            },
        ),
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(to='films_review.Genre'),
        ),
        migrations.AddField(
            model_name='film',
            name='writer',
            field=models.ManyToManyField(to='films_review.Writer'),
        ),
        migrations.AlterUniqueTogether(
            name='film',
            unique_together={('title', 'original_title', 'post_date')},
        ),
    ]
