# Generated by Django 3.2.9 on 2022-04-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='pub_date',
            new_name='post_date',
        ),
        migrations.AlterField(
            model_name='film',
            name='continuance',
            field=models.PositiveIntegerField(help_text='mins.'),
        ),
        migrations.AlterField(
            model_name='film',
            name='small_img',
            field=models.ImageField(default='film_img/default.jpg', upload_to='film_img/'),
        ),
    ]
